# La librairie Pandas

## Introduction

Pandas utilise une structure de données : DataFrame

- On peut stocker différents types de données dans un DataFrame

- Valeurs manquantes NaN sont faciles à remplacer

- facilité pour extraire des valeurs

## Lire un ficher CSV avec Pandas

In [2]:
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [ ]:
# Lire le ficher csv dans un dataframe
test = pd.read_csv("test.csv")

### Exercice

- Importer la librairie pandas.

- Utiliser la fonction pandas.read_csv() pour lire le fichier "food_info.csv" (téléchargeable dans les ressources de cette vidéo) dans un dataframe qu'on nomme food_info.

- Utiliser les fonctions type() et print() pour afficher le type de food_info et confirmer qu'il s'agit d'un objet dataframe.

In [7]:
import pandas as pd

food_info = pd.read_csv("food_info.csv")

In [8]:
print(food_info)

      NDB_No                   Shrt_Desc  Water_(g)  Energ_Kcal  Protein_(g)  \
0       1001            BUTTER WITH SALT      15.87         717         0.85
1       1002    BUTTER WHIPPED WITH SALT      15.87         717         0.85
2       1003        BUTTER OIL ANHYDROUS       0.24         876         0.28
3       1004                 CHEESE BLUE      42.41         353        21.40
4       1005                CHEESE BRICK      41.11         371        23.24
...      ...                         ...        ...         ...          ...
8613   83110             MACKEREL SALTED      43.00         305        18.50
8614   90240  SCALLOP (BAY&SEA) CKD STMD      70.25         111        20.54
8615   90480                  SYRUP CANE      26.00         269         0.00
8616   90560                   SNAIL RAW      79.20          90        16.10
8617   93600            TURTLE GREEN RAW      78.50          89        19.80

      Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  Fiber_TD_(g)  Sugar_Tot_(g)  \
0             81.11     2.11            0.06           0.0           0.06
1             81.11     2.11            0.06           0.0           0.06
2             99.48     0.00            0.00           0.0           0.00
3             28.74     5.11            2.34           0.0           0.50
4             29.68     3.18            2.79           0.0           0.51
...             ...      ...             ...           ...            ...
8613          25.10    13.40            0.00           0.0           0.00
8614           0.84     2.97            5.41           0.0           0.00
8615           0.00     0.86           73.14           0.0          73.20
8616           1.40     1.30            2.00           0.0           0.00
8617           0.50     1.20            0.00           0.0           0.00

      ...  Vit_A_IU  Vit_A_RAE  Vit_E_(mg)  Vit_D_mcg  Vit_D_IU  Vit_K_(mcg)  \
0     ...    2499.0      684.0        2.32        1.5      60.0          7.0
1     ...    2499.0      684.0        2.32        1.5      60.0          7.0
2     ...    3069.0      840.0        2.80        1.8      73.0          8.6
3     ...     721.0      198.0        0.25        0.5      21.0          2.4
4     ...    1080.0      292.0        0.26        0.5      22.0          2.5
...   ...       ...        ...         ...        ...       ...          ...
8613  ...     157.0       47.0        2.38       25.2    1006.0          7.8
8614  ...       5.0        2.0        0.00        0.0       2.0          0.0
8615  ...       0.0        0.0        0.00        0.0       0.0          0.0
8616  ...     100.0       30.0        5.00        0.0       0.0          0.1
8617  ...     100.0       30.0        0.50        0.0       0.0          0.1

      FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)  Cholestrl_(mg)
0         51.368       21.021        3.043           215.0
1         50.489       23.426        3.012           219.0
2         61.924       28.732        3.694           256.0
3         18.669        7.778        0.800            75.0
4         18.764        8.598        0.784            94.0
...          ...          ...          ...             ...
8613       7.148        8.320        6.210            95.0
8614       0.218        0.082        0.222            41.0
8615       0.000        0.000        0.000             0.0
8616       0.361        0.259        0.252            50.0
8617       0.127        0.088        0.170            50.0

[8618 rows x 36 columns]

In [9]:
print(type(food_info))

<class 'pandas.core.frame.DataFrame'>

## Exploration du dataframe

In [10]:
# head()

In [11]:
food_info = pd.read_csv("food_info.csv")

In [12]:
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0

In [13]:
# Afficher les 2 prémiéres lignes 
print(food_info.head(2))

   NDB_No                 Shrt_Desc  Water_(g)  Energ_Kcal  Protein_(g)  \
0    1001          BUTTER WITH SALT      15.87         717         0.85
1    1002  BUTTER WHIPPED WITH SALT      15.87         717         0.85

   Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  Fiber_TD_(g)  Sugar_Tot_(g)  ...  \
0          81.11     2.11            0.06           0.0           0.06  ...
1          81.11     2.11            0.06           0.0           0.06  ...

   Vit_A_IU  Vit_A_RAE  Vit_E_(mg)  Vit_D_mcg  Vit_D_IU  Vit_K_(mcg)  \
0    2499.0      684.0        2.32        1.5      60.0          7.0
1    2499.0      684.0        2.32        1.5      60.0          7.0

   FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)  Cholestrl_(mg)
0      51.368       21.021        3.043           215.0
1      50.489       23.426        3.012           219.0

[2 rows x 36 columns]

In [14]:
# Afficher le total des colonnes
columns_names = food_info.columns
print(columns_names)

Index(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg',
       'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)',
       'Cholestrl_(mg)'],
      dtype='object')

In [16]:
# Fonction Shape = Connaître la dimensions de mon tableau

In [17]:
# Dimensions du dataframe
dimensions = food_info.shape
print(dimensions)

(8618, 36)

In [18]:
# Nombres de lignes
num_rows = dimensions[0]
print(num_rows)

8618

In [19]:
# Nombre de colonnes
num_cols = dimensions[1]
print(num_cols)

36

## Sélectionner une ligne

In [20]:
# loc[]

In [21]:
# Objet Series représentant le ligne d'index 0 ou de position 1
food_info.loc[0]

NDB_No                         1001
Shrt_Desc          BUTTER WITH SALT
Water_(g)                     15.87
Energ_Kcal                      717
Protein_(g)                    0.85
Lipid_Tot_(g)                 81.11
Ash_(g)                        2.11
Carbohydrt_(g)                 0.06
Fiber_TD_(g)                    0.0
Sugar_Tot_(g)                  0.06
Calcium_(mg)                   24.0
Iron_(mg)                      0.02
Magnesium_(mg)                  2.0
Phosphorus_(mg)                24.0
Potassium_(mg)                 24.0
Sodium_(mg)                   643.0
Zinc_(mg)                      0.09
Copper_(mg)                     0.0
Manganese_(mg)                  0.0
Selenium_(mcg)                  1.0
Vit_C_(mg)                      0.0
Thiamin_(mg)                  0.005
Riboflavin_(mg)               0.034
Niacin_(mg)                   0.042
Vit_B6_(mg)                   0.003
Vit_B12_(mcg)                  0.17
Vit_A_IU                     2499.0
Vit_A_RAE                     684.0
Vit_E_(mg)                     2.32
Vit_D_mcg                       1.5
Vit_D_IU                       60.0
Vit_K_(mcg)                     7.0
FA_Sat_(g)                   51.368
FA_Mono_(g)                  21.021
FA_Poly_(g)                   3.043
Cholestrl_(mg)                215.0
Name: 0, dtype: object

In [22]:
food_info.loc[6]

NDB_No                         1007
Shrt_Desc          CHEESE CAMEMBERT
Water_(g)                      51.8
Energ_Kcal                      300
Protein_(g)                    19.8
Lipid_Tot_(g)                 24.26
Ash_(g)                        3.68
Carbohydrt_(g)                 0.46
Fiber_TD_(g)                    0.0
Sugar_Tot_(g)                  0.46
Calcium_(mg)                  388.0
Iron_(mg)                      0.33
Magnesium_(mg)                 20.0
Phosphorus_(mg)               347.0
Potassium_(mg)                187.0
Sodium_(mg)                   842.0
Zinc_(mg)                      2.38
Copper_(mg)                   0.021
Manganese_(mg)                0.038
Selenium_(mcg)                 14.5
Vit_C_(mg)                      0.0
Thiamin_(mg)                  0.028
Riboflavin_(mg)               0.488
Niacin_(mg)                    0.63
Vit_B6_(mg)                   0.227
Vit_B12_(mcg)                   1.3
Vit_A_IU                      820.0
Vit_A_RAE                     241.0
Vit_E_(mg)                     0.21
Vit_D_mcg                       0.4
Vit_D_IU                       18.0
Vit_K_(mcg)                     2.0
FA_Sat_(g)                   15.259
FA_Mono_(g)                   7.023
FA_Poly_(g)                   0.724
Cholestrl_(mg)                 72.0
Name: 6, dtype: object

In [23]:
type(food_info.loc[0])

pandas.core.series.Series

In [25]:
# Series c'est quoi ? 
# Structure de données qu'utilise Pandas pour représenter des lignes et des colonnes

### Exercice

- Assigner la 100e ligne du dataframe food_info à la variable row_100
- Afficher le résultat

In [27]:
row_100 = food_info.loc[99]
print(row_100)

NDB_No                                  1111
Shrt_Desc          MILK SHAKES THICK VANILLA
Water_(g)                              74.45
Energ_Kcal                               112
Protein_(g)                             3.86
Lipid_Tot_(g)                           3.03
Ash_(g)                                 0.91
Carbohydrt_(g)                         17.75
Fiber_TD_(g)                             0.0
Sugar_Tot_(g)                          17.75
Calcium_(mg)                           146.0
Iron_(mg)                                0.1
Magnesium_(mg)                          12.0
Phosphorus_(mg)                        115.0
Potassium_(mg)                         183.0
Sodium_(mg)                             95.0
Zinc_(mg)                               0.39
Copper_(mg)                            0.051
Manganese_(mg)                         0.014
Selenium_(mcg)                           2.3
Vit_C_(mg)                               0.0
Thiamin_(mg)                            0.03
Riboflavin_(mg)                        0.195
Niacin_(mg)                            0.146
Vit_B6_(mg)                            0.042
Vit_B12_(mcg)                           0.52
Vit_A_IU                                91.0
Vit_A_RAE                               25.0
Vit_E_(mg)                              0.05
Vit_D_mcg                                1.2
Vit_D_IU                                48.0
Vit_K_(mcg)                              0.2
FA_Sat_(g)                             1.886
FA_Mono_(g)                            0.875
FA_Poly_(g)                            0.113
Cholestrl_(mg)                          12.0
Name: 99, dtype: object

## Les types de données Pandas

In [28]:
row_100 = food_info.loc[99]
print(row_100)

NDB_No                                  1111
Shrt_Desc          MILK SHAKES THICK VANILLA
Water_(g)                              74.45
Energ_Kcal                               112
Protein_(g)                             3.86
Lipid_Tot_(g)                           3.03
Ash_(g)                                 0.91
Carbohydrt_(g)                         17.75
Fiber_TD_(g)                             0.0
Sugar_Tot_(g)                          17.75
Calcium_(mg)                           146.0
Iron_(mg)                                0.1
Magnesium_(mg)                          12.0
Phosphorus_(mg)                        115.0
Potassium_(mg)                         183.0
Sodium_(mg)                             95.0
Zinc_(mg)                               0.39
Copper_(mg)                            0.051
Manganese_(mg)                         0.014
Selenium_(mcg)                           2.3
Vit_C_(mg)                               0.0
Thiamin_(mg)                            0.03
Riboflavin_(mg)                        0.195
Niacin_(mg)                            0.146
Vit_B6_(mg)                            0.042
Vit_B12_(mcg)                           0.52
Vit_A_IU                                91.0
Vit_A_RAE                               25.0
Vit_E_(mg)                              0.05
Vit_D_mcg                                1.2
Vit_D_IU                                48.0
Vit_K_(mcg)                              0.2
FA_Sat_(g)                             1.886
FA_Mono_(g)                            0.875
FA_Poly_(g)                            0.113
Cholestrl_(mg)                          12.0
Name: 99, dtype: object

In [29]:
# Object

In [30]:
# int

In [31]:
# float

In [32]:
# datetime

In [33]:
# bool

In [34]:
# dataframe.dtypes

In [36]:
# Afficher les types de données de chaque colonne
print(food_info.dtypes)

NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)       float64
Iron_(mg)          float64
Magnesium_(mg)     float64
Phosphorus_(mg)    float64
Potassium_(mg)     float64
Sodium_(mg)        float64
Zinc_(mg)          float64
Copper_(mg)        float64
Manganese_(mg)     float64
Selenium_(mcg)     float64
Vit_C_(mg)         float64
Thiamin_(mg)       float64
Riboflavin_(mg)    float64
Niacin_(mg)        float64
Vit_B6_(mg)        float64
Vit_B12_(mcg)      float64
Vit_A_IU           float64
Vit_A_RAE          float64
Vit_E_(mg)         float64
Vit_D_mcg          float64
Vit_D_IU           float64
Vit_K_(mcg)        float64
FA_Sat_(g)         float64
FA_Mono_(g)        float64
FA_Poly_(g)        float64
Cholestrl_(mg)     float64
dtype: object

## Sélectionner plusieurs lignes

In [37]:
# Dataframe contenant les lignes d'index 3, 4, 5, et 6
food_info.loc[3:6]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0
6,1007,CHEESE CAMEMBERT,51.80,300,19.80,24.26,3.68,0.46,0.0,0.46,...,820.0,241.0,0.21,0.4,18.0,2.0,15.259,7.023,0.724,72.0

In [38]:
# Dataframe contenant les lignes d'index 2, 5 et 10
# Méthode 1

In [39]:
two_five_ten = [2, 5, 10]
food_info.loc[two_five_ten]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0
10,1011,CHEESE COLBY,38.20,394,23.76,32.11,3.36,2.57,0.0,0.52,...,994.0,264.0,0.28,0.6,24.0,2.7,20.218,9.280,0.953,95.0

In [40]:
# Dataframe contenant les lignes d'index 2, 5 et 10
# Méthode 2

In [41]:
food_info.loc[[2, 5, 10]]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0
10,1011,CHEESE COLBY,38.20,394,23.76,32.11,3.36,2.57,0.0,0.52,...,994.0,264.0,0.28,0.6,24.0,2.7,20.218,9.280,0.953,95.0

### Exercice

- Sélectionner les 5 dernières lignes de food_info et assigner le résultat à la variable last_rows

In [43]:
food_info.shape

(8618, 36)

In [46]:
last_rows = [8613, 8614, 8615, 8616, 8617]
food_info.loc[last_rows]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.0,...,157.0,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.0,...,5.0,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.2,...,0.0,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.0,...,100.0,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.0,...,100.0,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0

## Sélectionner une colonne plutôt qu'une ligne

In [47]:
# Objet Series représentant la colonne "NDB_No".
# Méthode 1
ndb_col = food_info["NDB_No"]

In [48]:
# Intervenir une variable pour le nom de la colonne
# Méthode 2 
col_name = "NDB_No"
ndb_col = food_info[col_name]

In [49]:
print(ndb_col)

0        1001
1        1002
2        1003
3        1004
4        1005
        ...
8613    83110
8614    90240
8615    90480
8616    90560
8617    93600
Name: NDB_No, Length: 8618, dtype: int64

### Exercice

- Assigner la colonne "protein_(g)" à la variable protein.

- Assigner la colonne "Cholestrl_(mg)" à la variable cholesterol.

- Afficher les résultats.

In [58]:
protein = food_info["Protein_(g)"]
cholesterol = food_info["Cholestrl_(mg)"]

In [59]:
print(protein)

0        0.85
1        0.85
2        0.28
3       21.40
4       23.24
        ...
8613    18.50
8614    20.54
8615     0.00
8616    16.10
8617    19.80
Name: Protein_(g), Length: 8618, dtype: float64

In [60]:
print(cholesterol)

0       215.0
1       219.0
2       256.0
3        75.0
4        94.0
        ...
8613     95.0
8614     41.0
8615      0.0
8616     50.0
8617     50.0
Name: Cholestrl_(mg), Length: 8618, dtype: float64

## Sélectionner plusieurs colonnes

In [61]:
# Méthode intermédiaire avec une variable
columns = ["Zinc_(mg)", "Copper_(mg)"]
zinc_copper = food_info[columns]

In [62]:
# Méthode Direct 
zinc_copper = food_info[["Zinc_(mg)", "Copper_(mg)"]]

In [63]:
print(zinc_copper)

      Zinc_(mg)  Copper_(mg)
0          0.09        0.000
1          0.05        0.016
2          0.01        0.001
3          2.66        0.040
4          2.60        0.024
...         ...          ...
8613       1.10        0.100
8614       1.55        0.033
8615       0.19        0.020
8616       1.00        0.400
8617       1.00        0.250

[8618 rows x 2 columns]

### Exercice

- Sélectionner les colonnes "Shrt_Desc", "Selenium(mcg)" et "Thiamin_(mg)" et assigner la dataframe résultant à la variable selenium_thiamin.

- Afficher le résultat

In [65]:
selenium_thiamin = food_info[["Shrt_Desc", "Selenium_(mcg)", "Thiamin_(mg)"]]
print(selenium_thiamin)

                       Shrt_Desc  Selenium_(mcg)  Thiamin_(mg)
0               BUTTER WITH SALT             1.0         0.005
1       BUTTER WHIPPED WITH SALT             1.0         0.005
2           BUTTER OIL ANHYDROUS             0.0         0.001
3                    CHEESE BLUE            14.5         0.029
4                   CHEESE BRICK            14.5         0.014
...                          ...             ...           ...
8613             MACKEREL SALTED            73.4         0.020
8614  SCALLOP (BAY&SEA) CKD STMD            21.7         0.012
8615                  SYRUP CANE             0.7         0.130
8616                   SNAIL RAW            27.4         0.010
8617            TURTLE GREEN RAW            16.8         0.120

[8618 rows x 3 columns]

## Cas Pratique

Sélectionner et afficher seulement les colonnes qui utilisent comme unité de mesure les grammes (c'est à dire qui se terminent par "(g)"). Pour cela :

        - Utiliser l'attribut columns pour retourner le nom des colonnes du dataframe food_info et convertir en liste utilisant la méthode tolist()

        - Créer une nouvelle liste qu'on nommera gram_columns, contenant seulement les colonnes se terminant par "(g)". Indice : la méthode endswith() retourne True si l'objet sur lequel on l'applique se termine par l'élément entre parenthèses. ex : total(g).endswith("(g)") retourne True. Une boucle for est fortement conseillé pour parcourir tous les noms de colonne.

        - Sélectionner les colonnes de gram_columns pour le dataframe food_info et assigner le dataframe résultat à la variable gram_df

        - Afficher les 3 premières valeurs de ce dataframe gram_df

In [68]:
# Utiliser l'attribut columns pour retourner le nom des colonnes du dataframe food_info et convertir en liste utilisant la méthode tolist()
col_names = food_info.columns.tolist()

# Créer une nouvelle liste qu'on nommera gram_columns, contenant seulement les colonnes se terminant par "(g)"
gram_columns = []

# Boucle For
for c in col_names: 
    if c.endswith("(g)"):
        gram_columns.append(c)

# Création d'un nouveau dataframe food_info
gram_df = food_info[gram_columns]

# Afficher les 3 premères valeurs de ce dataframe gram_df
gram_df.head(3)

,Water_(g),Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g)
0,15.87,0.85,81.11,2.11,0.06,0.0,0.06,51.368,21.021,3.043
1,15.87,0.85,81.11,2.11,0.06,0.0,0.06,50.489,23.426,3.012
2,0.24,0.28,99.48,0.00,0.00,0.0,0.00,61.924,28.732,3.694