# Manipulation de données avec Pandas

## Introduction

In [1]:
# Score = 2 x protein - 0.75 x Lipid

- Importer la librairie pandas.

- Lire le fichier "food_info.csv" dans un dataframe qu'on nommera food_info.

- Utiliser l'attribut Dataframe.columns suivi de la méthode Index.tolist() pour retourner une liste contenant tous les noms de colonne de food_info.

- Assigner la liste résultante à la variable col_names et utiliser la fonction print() pour afficher le nom des colonnes.

- Enfin afficher les 3 premiers éléments de food_info.

In [2]:
import pandas as pd

food_info = pd.read_csv("food_info.csv")
# Dataframe.columns suivi de la méthode Index.tolist()
col_names = food_info.columns.tolist()

In [3]:
print(col_names)

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']

In [9]:
# Afficher les 3 premiers éléments de food_info.
food_info.head(3)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0

## Transformer une colonne

In [11]:
div_1000 = food_info["Iron_(mg)"] / 1000

In [12]:
div_1000

0       0.00002
1       0.00016
2       0.00000
3       0.00031
4       0.00043
         ...
8613    0.00140
8614    0.00058
8615    0.00360
8616    0.00350
8617    0.00140
Name: Iron_(mg), Length: 8618, dtype: float64

In [15]:
iron = food_info["Iron_(mg)"]
iron

0       0.02
1       0.16
2       0.00
3       0.31
4       0.43
        ...
8613    1.40
8614    0.58
8615    3.60
8616    3.50
8617    1.40
Name: Iron_(mg), Length: 8618, dtype: float64

In [16]:
# Ajoute 100 à chaque valeur dans la colonne et retourne un nouvel objet Series
add_100 = food_info["Iron_(mg)"] + 100

In [17]:
# Soustraire 100 à chaque valeur dans la colonne et retourne un nouvel objet Series 
supp_100 = food_info["Iron_(mg)"] - 100

In [19]:
# Multiplier chaque valeur de la colonne par 2
mult_2 = food_info["Iron_(mg)"] * 2

### Exercice

Transformer une colonne

 - Diviser la colonne "Sodium_(mg)" par 1000 pour convertir cette colonne en grammes et assigner le résultat à la variable sodium_grams.

 - Multiplier la colonne "Sugar_Tot(g)" par 1000 pour convertir en milligrammes et assigner le résultat à la variable sugar_milligrams.

In [20]:
# Diviser la colonne par 1000
sodium_grams = food_info["Sodium_(mg)"] / 1000

In [21]:
# Multiplier la colonne par 1000
sugar_milligrams = food_info["Sugar_Tot_(g)"] * 1000

In [22]:
print(sodium_grams)

0       0.643
1       0.659
2       0.002
3       1.146
4       0.560
        ...
8613    4.450
8614    0.667
8615    0.058
8616    0.070
8617    0.068
Name: Sodium_(mg), Length: 8618, dtype: float64

In [23]:
print(sugar_milligrams)

0          60.0
1          60.0
2           0.0
3         500.0
4         510.0
         ...
8613        0.0
8614        0.0
8615    73200.0
8616        0.0
8617        0.0
Name: Sugar_Tot_(g), Length: 8618, dtype: float64

## Opérations mathématiques entre colonnes

In [24]:
# Multiplication entre colonnes
water_energy = food_info["Water_(g)"] * food_info["Energ_Kcal"]

In [26]:
print(water_energy[0:5])

0    11378.79
1    11378.79
2      210.24
3    14970.73
4    15251.81
dtype: float64

In [28]:
print(food_info[["Water_(g)", "Energ_Kcal"]][0:5])

   Water_(g)  Energ_Kcal
0      15.87         717
1      15.87         717
2       0.24         876
3      42.41         353
4      41.11         371

### Exercice

Opérations mathématiques entre colonnes

 - Diviser la colonne "Protein_(g)" par la colonne "Water_(g)" et assigner le résultat à la variable grams_of_protein_per_gram_of_water.

 - Additionner les colonnes "Calcium_(mg)" et "Iron_(mg)" et assigner le résultat à la variable milligrams_of_calcium_and_iron.

 - Afficher les résultats.

In [29]:
# Division entre colonnes
grams_of_protein_per_gram_of_water = food_info["Protein_(g)"] / food_info["Water_(g)"]

# Aditionner entre colonnes
milligrams_of_calcium_and_iron = food_info["Calcium_(mg)"] + food_info["Iron_(mg)"]

In [31]:
print(grams_of_protein_per_gram_of_water)

0       0.053560
1       0.053560
2       1.166667
3       0.504598
4       0.565313
          ...
8613    0.430233
8614    0.292384
8615    0.000000
8616    0.203283
8617    0.252229
Length: 8618, dtype: float64

In [32]:
print(milligrams_of_calcium_and_iron)

0        24.02
1        24.16
2         4.00
3       528.31
4       674.43
         ...
8613     67.40
8614     10.58
8615     16.60
8616     13.50
8617    119.40
Length: 8618, dtype: float64

## Créer un indice nutritionnel

Score = 2 x (Protein_(g)) - 0.75 x (LipidTot(g))

 - Multiplier la colonne "Protein_(g)" par 2 et assigner le résultat à la variable protein.

 - Multiplier la colonne "Lipid_Tot_(g)" par -0.75 et assigner le résultat à la variable fat.

 -Additionner les variables ensemble et assigner le résultat à la variable rating.
 
 - Afficher le résultat.

In [42]:
# Multiplier la colonne "Protein_(g)" par 2 et assigner le résultat à la variable protein.
protein = food_info["Protein_(g)"] * 2

In [43]:
# Multiplier la colonne "Lipid_Tot_(g)" par -0.75 et assigner le résultat à la variable fat.
fat = food_info["Lipid_Tot_(g)"] * (-0.75)

In [44]:
# Additionner les variables ensemble et assigner le résultat à la variable rating.
rating = fat + protein

In [45]:
print(rating)

0      -59.1325
1      -59.1325
2      -74.0500
3       21.2450
4       24.2200
         ...
8613    18.1750
8614    40.4500
8615     0.0000
8616    31.1500
8617    39.2250
Length: 8618, dtype: float64

## Normaliser des colonnes

In [46]:
# Series.max()

In [47]:
# Valeur max de la colonne "Energ_Kcal"
max_calories = food_info["Energ_Kcal"].max()
print(max_calories)

902

In [49]:
# Diviser les valeurs de la colonne "Energ_Kcal" par la valeur max de cette même colonne
normalized_calories = food_info["Energ_Kcal"] / max_calories
print(normalized_calories)

0       0.794900
1       0.794900
2       0.971175
3       0.391353
4       0.411308
          ...
8613    0.338137
8614    0.123060
8615    0.298226
8616    0.099778
8617    0.098670
Name: Energ_Kcal, Length: 8618, dtype: float64

### Exercice

Normaliser des colonnes

 - Normaliser les valeurs de la colonne "Protein_(g)" et assigner le résultat à la variable normalized_protein.

 - Normaliser les valeurs de la colonne "Lipid_Tot_(g)" et assigner le résultat à la variable normalized_fat.

In [50]:
# Normaliser les valeurs de la colonne "Protein_(g)" et assigner le résultat à la variable normalized_protein
normalized_protein = food_info["Protein_(g)"] / food_info["Protein_(g)"].max()

In [51]:
# Normaliser les valeurs de la colonne "LipidTot(g)" et assigner le résultat à la variable normalized_fat
normalized_fat = food_info["Lipid_Tot_(g)"] / food_info["Lipid_Tot_(g)"].max()

In [52]:
print(normalized_protein)

0       0.009624
1       0.009624
2       0.003170
3       0.242301
4       0.263134
          ...
8613    0.209466
8614    0.232563
8615    0.000000
8616    0.182292
8617    0.224185
Name: Protein_(g), Length: 8618, dtype: float64

In [53]:
print(normalized_fat)

0       0.8111
1       0.8111
2       0.9948
3       0.2874
4       0.2968
         ...
8613    0.2510
8614    0.0084
8615    0.0000
8616    0.0140
8617    0.0050
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

## Créer une nouvelle colonne

In [54]:
iron_grams = food_info["Iron_(mg)"] / 1000
food_info["Iron_(g)"] = iron_grams

In [55]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.00002
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.00016
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.00000
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.00031
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.00043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.00140
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.00058
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.00360
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.00350
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.00140

### Exercice

Créer une nouvelle colonne

 - Assigner la colonne normalisée représentée par la variable normalized_protein à la nouvelle colonne qu'on nommera "Normalized_Protein" dans le dataframe food_info.

 - Assigner la colonne normalisée représentée par la variable normalized_fat à la nouvelle colonne qu'on nommera "Normalized_Fat" dans le dataframe food_info.

 - Afficher les 5 premières valeurs du dataframe food_info.

In [56]:
normalized_protein = food_info["Protein_(g)"] / food_info["Protein_(g)"].max()
food_info["Normalized_Protein"] = normalized_protein

In [61]:
normalized_fat = food_info["Lipid_Tot_(g)"] / food_info["Lipid_Tot_(g)"].max()
food_info["Normalized_Fat"] = normalized_fat

In [65]:
food_info[0:5]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_fat,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,51.368,21.021,3.043,215.0,0.00002,0.009624,0.8111,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,50.489,23.426,3.012,219.0,0.00016,0.009624,0.8111,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,8.6,61.924,28.732,3.694,256.0,0.00000,0.003170,0.9948,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,2.4,18.669,7.778,0.800,75.0,0.00031,0.242301,0.2874,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,2.5,18.764,8.598,0.784,94.0,0.00043,0.263134,0.2968,0.2968,0.303668

## Créer une colonne pour l'indice nutritionnel normalisé

Score = 2 x Normalized_Protein - 0.75 x Normalized_Fat

 - Utiliser les colonnes Normalized_Protein et Normalized_Fat avec cette formule pour créer une nouvelle colonne qu'on nommera Norm_Nutr_Index.

In [64]:
food_info["Norm_Nutr_Index"] = 2 * food_info["Normalized_Protein"] + (-0.75) * food_info["Normalized_Fat"]

In [69]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_fat,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,51.368,21.021,3.043,215.0,0.00002,0.009624,0.8111,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,50.489,23.426,3.012,219.0,0.00016,0.009624,0.8111,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,8.6,61.924,28.732,3.694,256.0,0.00000,0.003170,0.9948,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,2.4,18.669,7.778,0.800,75.0,0.00031,0.242301,0.2874,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,2.5,18.764,8.598,0.784,94.0,0.00043,0.263134,0.2968,0.2968,0.303668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,7.8,7.148,8.320,6.210,95.0,0.00140,0.209466,0.2510,0.2510,0.230681
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,0.0,0.218,0.082,0.222,41.0,0.00058,0.232563,0.0084,0.0084,0.458827
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.000,0.000,0.000,0.0,0.00360,0.000000,0.0000,0.0000,0.000000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,0.1,0.361,0.259,0.252,50.0,0.00350,0.182292,0.0140,0.0140,0.354083
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,0.1,0.127,0.088,0.170,50.0,0.00140,0.224185,0.0050,0.0050,0.444620

## Trier un DataFrame

In [70]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_fat,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,51.368,21.021,3.043,215.0,0.00002,0.009624,0.8111,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,50.489,23.426,3.012,219.0,0.00016,0.009624,0.8111,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,8.6,61.924,28.732,3.694,256.0,0.00000,0.003170,0.9948,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,2.4,18.669,7.778,0.800,75.0,0.00031,0.242301,0.2874,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,2.5,18.764,8.598,0.784,94.0,0.00043,0.263134,0.2968,0.2968,0.303668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,7.8,7.148,8.320,6.210,95.0,0.00140,0.209466,0.2510,0.2510,0.230681
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,0.0,0.218,0.082,0.222,41.0,0.00058,0.232563,0.0084,0.0084,0.458827
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.000,0.000,0.000,0.0,0.00360,0.000000,0.0000,0.0000,0.000000
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,0.1,0.361,0.259,0.252,50.0,0.00350,0.182292,0.0140,0.0140,0.354083
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,0.1,0.127,0.088,0.170,50.0,0.00140,0.224185,0.0050,0.0050,0.444620

In [72]:
# sort_values()

In [73]:
food_info.sort_values("Water_(g)")

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_fat,Normalized_Fat,Norm_Nutr_Index
676,4544,SHORTENING HOUSEHOLD LARD&VEG OIL,0.0,900,0.00,100.00,0.0,0.00,0.0,0.00,...,21.5,40.300,44.4,10.9,56.0,0.00000,0.000000,1.0000,1.0000,-0.750000
664,4520,FAT MUTTON TALLOW,0.0,902,0.00,100.00,0.0,0.00,0.0,0.00,...,0.0,47.300,40.6,7.8,102.0,0.00000,0.000000,1.0000,1.0000,-0.750000
665,4528,OIL WALNUT,0.0,884,0.00,100.00,0.0,0.00,0.0,0.00,...,15.0,9.100,22.8,63.3,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000
666,4529,OIL ALMOND,0.0,884,0.00,100.00,0.0,0.00,0.0,0.00,...,7.0,8.200,69.9,17.4,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000
667,4530,OIL APRICOT KERNEL,0.0,884,0.00,100.00,0.0,0.00,0.0,0.00,...,NaN,6.300,60.0,29.3,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6067,19084,CANDIES HERSHEY'S GOLDEN ALMOND SOLITAIRES,NaN,570,11.97,37.13,NaN,46.91,4.4,37.13,...,NaN,15.230,NaN,NaN,13.0,0.00250,0.135530,0.3713,0.3713,-0.007415
6095,19112,CANDIES TWIZZLERS STRAWBERRY TWISTS CANDY,NaN,350,2.56,2.32,NaN,79.74,0.0,39.64,...,NaN,0.000,NaN,NaN,0.0,0.00051,0.028986,0.0232,0.0232,0.040571
6113,19130,CANDIES HERSHEY'S POT OF GOLD ALMOND BAR,NaN,577,12.82,38.46,NaN,46.15,3.8,38.46,...,NaN,16.667,NaN,NaN,13.0,0.00185,0.145154,0.3846,0.3846,0.001858
6150,19171,COCOA DRY PDR UNSWTND HERSHEY'S EUROPEAN STYLE...,NaN,400,20.00,10.00,NaN,60.00,20.0,0.00,...,NaN,0.000,NaN,NaN,0.0,0.03600,0.226449,0.1000,0.1000,0.377899
7776,28039,KASHI TLC HAPPY TRAIL MIX COOKIES,NaN,453,8.10,18.10,NaN,69.40,13.7,26.60,...,NaN,4.100,7.8,5.6,0.0,NaN,0.091712,0.1810,0.1810,0.047674

In [76]:
# Affichage d'une colonne par ordre décroissant
food_info.sort_values("Water_(g)", inplace=True, ascending=False)

In [77]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_fat,Normalized_Fat,Norm_Nutr_Index
4209,14076,BEVERAGES ICELANDIC GLACIAL NAT SPRING H2O,100.0,0,0.00,0.00,0.0,0.00,0.0,0.00,...,0.0,0.000,0.0,0.0,0.0,0.00000,0.000000,0.0000,0.0000,0.000000
4376,14437,WATER BTLD NON-CARBONATED CALISTOGA,100.0,0,0.00,0.00,0.1,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0000,0.0000,0.000000
4348,14385,WATER BTLD POLAND SPRING,100.0,0,0.00,0.00,0.0,0.00,0.0,NaN,...,NaN,0.000,0.0,0.0,0.0,0.00001,0.000000,0.0000,0.0000,0.000000
4378,14439,WATER BTLD NON-CARBONATED NAYA,100.0,0,0.00,0.00,0.1,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0000,0.0000,0.000000
4377,14438,WATER BTLD NON-CARBONATED CRYSTAL GEYSER,100.0,0,0.00,0.00,0.1,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0000,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6067,19084,CANDIES HERSHEY'S GOLDEN ALMOND SOLITAIRES,NaN,570,11.97,37.13,NaN,46.91,4.4,37.13,...,NaN,15.230,NaN,NaN,13.0,0.00250,0.135530,0.3713,0.3713,-0.007415
6095,19112,CANDIES TWIZZLERS STRAWBERRY TWISTS CANDY,NaN,350,2.56,2.32,NaN,79.74,0.0,39.64,...,NaN,0.000,NaN,NaN,0.0,0.00051,0.028986,0.0232,0.0232,0.040571
6113,19130,CANDIES HERSHEY'S POT OF GOLD ALMOND BAR,NaN,577,12.82,38.46,NaN,46.15,3.8,38.46,...,NaN,16.667,NaN,NaN,13.0,0.00185,0.145154,0.3846,0.3846,0.001858
6150,19171,COCOA DRY PDR UNSWTND HERSHEY'S EUROPEAN STYLE...,NaN,400,20.00,10.00,NaN,60.00,20.0,0.00,...,NaN,0.000,NaN,NaN,0.0,0.03600,0.226449,0.1000,0.1000,0.377899
7776,28039,KASHI TLC HAPPY TRAIL MIX COOKIES,NaN,453,8.10,18.10,NaN,69.40,13.7,26.60,...,NaN,4.100,7.8,5.6,0.0,NaN,0.091712,0.1810,0.1810,0.047674

### Exercice

Trier un DataFrame

 - Remplacer le dataframe food_info en triant par rapport à la colonne Norm_Nutr_Index de façon décroissante (du plus grand au plus petit)

In [78]:
food_info.sort_values("Norm_Nutr_Index", inplace=True, ascending=False)

In [79]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_fat,Normalized_Fat,Norm_Nutr_Index
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.0,0.066,0.101,0.258,0.0,0.01450,1.000000,0.0053,0.0053,1.996025
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.0,0.070,0.060,0.010,0.0,0.00111,0.969203,0.0010,0.0010,1.937656
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.0,0.147,0.173,0.070,20.0,0.00023,0.958220,0.0048,0.0048,1.912840
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.0,0.000,0.000,0.000,0.0,0.00024,0.932971,0.0004,0.0004,1.865642
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,NaN,0.600,1.330,0.370,NaN,0.04960,0.935236,0.0230,0.0230,1.853221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,4582,OIL CANOLA,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,71.3,7.365,63.276,28.142,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000
695,4583,OIL MUSTARD,0.00,884,0.00,100.00,0.00,0.00,0.0,NaN,...,NaN,11.582,59.187,21.230,NaN,0.00000,0.000000,1.0000,1.0000,-0.750000
696,4584,OIL SUNFLOWER HI OLEIC (70% & OVER),0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,5.4,9.859,83.689,3.798,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000
632,4038,OIL WHEAT GERM,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,24.7,18.800,15.100,61.700,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000
662,4517,OIL GRAPESEED,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,NaN,9.600,16.100,69.900,0.0,0.00000,0.000000,1.0000,1.0000,-0.750000