# Traiter les valeurs manquantes

## Introduction au dataset

In [1]:
import pandas as pd

titanic_survival = pd.read_csv("titanic_survival.csv")
titanic_survival.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

## Trouver les valeurs manquantes

In [ ]:
# pandas.isnull()

In [2]:
sex = titanic_survival["sex"]
sex_is_null = pd.isnull(sex)
print(sex_is_null)

0       False
1       False
2       False
3       False
4       False
        ...
1305    False
1306    False
1307    False
1308    False
1309     True
Name: sex, Length: 1310, dtype: bool

In [3]:
# Trouver les valeurs manquantes
sex_null = sex[sex_is_null]
print(sex_null)

1309    NaN
Name: sex, dtype: object

### Exercice

Lire le dataset titanic_survival.csv

Compter le nombre de valeurs dans la colonne "age" possédant des valeurs manquantes :

 - Assigner à la variable age la colonne des ages du dataframe titanic_survival

 - Utiliser pandas.isnull() sur la variable age pour créer une Series de valeurs True et False

 - Utiliser la Series résultante pour sélectionner seulement les éléments de la colonne "age" qui sont nuls et assigner le résultat à la variable age_null

 - Assigner le nombre de valeurs manquantes de age_null à la variable age_null_count (fonction len())

Afficher age_null_count pour voir le nombre de valeurs manquantes de la colonne "age"

In [4]:
import pandas as pd

titanic_survival = pd.read_csv("titanic_survival.csv")

In [5]:
age = titanic_survival["age"]
age_is_null = pd.isnull(age)
print(age_is_null)

0       False
1       False
2       False
3       False
4       False
        ...
1305     True
1306    False
1307    False
1308    False
1309     True
Name: age, Length: 1310, dtype: bool

In [6]:
age_null = age[age_is_null]
print(age_null)

15     NaN
37     NaN
40     NaN
46     NaN
59     NaN
        ..
1297   NaN
1302   NaN
1303   NaN
1305   NaN
1309   NaN
Name: age, Length: 264, dtype: float64

In [8]:
age_null_count = len(age_null)
print(age_null_count)

264

## Problème avec les valeurs manquantes

- Utiliser age_is_null pour créer un vecteur qui contient seulement les valeurs de la colonne "age" qui ne sont pas NaN (c'est à dire pour lesquelles age_is_null vaut False)

- Assigner ce résultat à la variable good_ages

- Calculer la moyenne de ce nouveau vecteur et assigner le résultat à la variable mean_age

- Afficher cette moyenne.

In [10]:
age_is_null = pd.isnull(titanic_survival["age"])

# Afficher tous les âges qui sont présent
good_ages = titanic_survival["age"][age_is_null == False]

# Calcul de la moyenne d'âge
mean_age = sum(good_ages) / len(good_ages)
print(mean_age)

29.8811345124283

## Calculer une moyenne plus rapidement

In [11]:
# Series.mean()

In [12]:
mean_age = titanic_survival["age"].mean()
print(mean_age)

29.8811345124283

### Exercice

Assigner la moyenne de la colonne "fare" à la variable mean_fare.

Afficher le résultat.

In [13]:
mean_fare = titanic_survival["fare"].mean()
print(mean_fare)

33.29547928134557

## Calculer des statistiques de prix

- Créer un dictionnaire vide qu'on nommera fares_by_class

- Créer la liste passenger_classes qui contient les éléments [1,2,3].

- Utiliser une boucle for pour parcourir la liste passenger_classes :

    - Sélectionner juste les lignes de titanic_survival pour lesquelles la colonne pclass est égale à la variable temporaire (l'itérateur) de la boucle for, c'est à dire correspondant au numéro de classe (1, 2 ou 3)

    - Sélectionner seulement la colonne fare pour ce sous-ensemble de lignes (correspondant à la classe)

    - Utiliser la méthode Series.mean() pour calculer la moyenne de ce sous-ensemble

    - Ajouter cette moyenne calculée de la classe au dictionnaire fares_by_class avec comme clé le numéro de la classe (et donc comme valeur la moyenne du prix du billet d'embarquement)

- Une fois la boucle achevée, le dictionnaire fares_by_class devrait avoir 1,2 et 3 comme clés avec en valeur les moyennes correspondantes.

- Afficher le résultat.

In [16]:
fares_by_class = {}

passenger_classes = [1,2,3]

for this_class in passenger_classes:
    pclass_rows = titanic_survival[titanic_survival["pclass"] == this_class]
    pclass_fares = pclass_rows["fare"]
    fare_for_class = pclass_fares.mean()
    fares_by_class[this_class] = fare_for_class

print(fares_by_class)

{1: 87.50899164086688, 2: 21.179196389891697, 3: 13.302888700564973}

## Introduction aux pivots de table

In [17]:
# DataFrame.pivot_table()

In [19]:
import numpy
passenger_class_fares = titanic_survival.pivot_table(index="pclass", values="fare")

In [20]:
print(passenger_class_fares)

             fare
pclass
1.0     87.508992
2.0     21.179196
3.0     13.302889

- Utiliser la méthode dataFrame.pivot_table() pour calculer la moyenne de l'âge pour chaque classe de passager ("pclass").

- Assigner le résultat à la variable passenger_age.

- Afficher passenger_age.

- Faire de même avec la colonne survived pour chaque classe de passager.

In [22]:
passenger_age = titanic_survival.pivot_table(index="pclass", values="age")
print(passenger_age)

              age
pclass
1.0     39.159918
2.0     29.506705
3.0     24.816367

In [23]:
passenger_survived = titanic_survival.pivot_table(index="pclass", values="survived")
print(passenger_survived)

        survived
pclass
1.0     0.619195
2.0     0.429603
3.0     0.255289

## Tables Pivot Niveau 2

- Faire un pivot de table qui calcule le total d'argent encaissé ("fare") et le nombre total de survivants ("survived") pour chaque port d'embarcation ("embarked"). Il faudra utiliser la fonction numpy.sum

- Assigner le résultat à la variable port_stats.

- Afficher le résultat.

In [25]:
import numpy as np

port_stats = titanic_survival.pivot_table(index="embarked", values=["fare", "survived"], aggfunc=np.sum)
print(port_stats)

                fare  survived
embarked
C         16830.7922     150.0
Q          1526.3085      44.0
S         25033.3862     304.0

/var/folders/rg/f7ng39g91739cyddknxt75d40000gn/T/ipykernel_38646/3084884193.py:3: FutureWarning: The provided callable <function sum at 0x103bf5e40> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  port_stats = titanic_survival.pivot_table(index="embarked", values=["fare", "survived"], aggfunc=np.sum)

## Eliminer les valeurs manquantes

In [26]:
# DataFrame.dropna(axis=0 ou axis='index') - axis=1

In [27]:
drop_na_rows = titanic_survival.dropna(axis=0)
drop_na_rows

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

In [31]:
drop_na_columns = titanic_survival.dropna(axis=1)
drop_na_columns

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1310 rows x 0 columns]

In [29]:
# dropna(axis=..., subset=["name"])

In [30]:
titanic_survival.dropna(axis=0, subset=["name"])

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN

### Exercice

- Supprimer toutes les lignes de titanic_survival pour lesquelles les colonnes "age" ou "sex" ont des valeurs manquantes et assigner le résultat à la variable new_titanic_survival.

- Comparer le nombre de lignes qu'il reste avec l'attribut shape.

In [32]:
new_titanic_survival = titanic_survival.dropna(axis=0, subset=["age", "sex"])
new_titanic_survival

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301,3.0,0.0,"Youseff, Mr. Gerious",male,45.5000,0.0,0.0,2628,7.2250,NaN,C,NaN,312.0,NaN
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [33]:
print(new_titanic_survival.shape)

(1046, 14)

## iloc pour accéder à des lignes

In [34]:
# DataFrame.loc[]

In [35]:
new_titanic_survival = titanic_survival.sort_values("age", inplace=False, ascending=False)
new_titanic_survival

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1302,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1303,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
new_titanic_survival.loc[0]

pclass                                 1.0
survived                               1.0
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                  0.0
parch                                  0.0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [37]:
# DataFrame.iloc[]

In [38]:
new_titanic_survival.iloc[0:5]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

### Exercice

- Assigner les 10 premières lignes de new_titanic_survival à la variable first_ten_rows.

- Assigner la 5e ligne de new_titanic_survival à la variable row_position-fifth.

- Assigner la ligne dont l'intitulé d'index est 25 pour new_titanic_survival à la variable row_index_25.

In [39]:
first_ten_rows = new_titanic_survival.iloc[0:10]
print(first_ten_rows)

      pclass  survived                                               name  \
14       1.0       1.0               Barkworth, Mr. Algernon Henry Wilson
61       1.0       1.0  Cavendish, Mrs. Tyrell William (Julia Florence...
1235     3.0       0.0                                Svensson, Mr. Johan
135      1.0       0.0                          Goldschmidt, Mr. George B
9        1.0       0.0                            Artagaveytia, Mr. Ramon
727      3.0       0.0                               Connors, Mr. Patrick
81       1.0       0.0                       Crosby, Capt. Edward Gifford
506      2.0       0.0                        Mitchell, Mr. Henry Michael
285      1.0       0.0                                 Straus, Mr. Isidor
594      2.0       0.0                              Wheadon, Mr. Edward H

         sex   age  sibsp  parch      ticket      fare    cabin embarked boat  \
14      male  80.0    0.0    0.0       27042   30.0000      A23        S    B
61    female  76.0    1.0    0.0       19877   78.8500      C46        S    6
1235    male  74.0    0.0    0.0      347060    7.7750      NaN        S  NaN
135     male  71.0    0.0    0.0    PC 17754   34.6542       A5        C  NaN
9       male  71.0    0.0    0.0    PC 17609   49.5042      NaN        C  NaN
727     male  70.5    0.0    0.0      370369    7.7500      NaN        Q  NaN
81      male  70.0    1.0    1.0   WE/P 5735   71.0000      B22        S  NaN
506     male  70.0    0.0    0.0  C.A. 24580   10.5000      NaN        S  NaN
285     male  67.0    1.0    0.0    PC 17483  221.7792  C55 C57        S  NaN
594     male  66.0    0.0    0.0  C.A. 24579   10.5000      NaN        S  NaN

       body                                     home.dest
14      NaN                                 Hessle, Yorks
61      NaN                       Little Onn Hall, Staffs
1235    NaN                                           NaN
135     NaN                                  New York, NY
9      22.0                           Montevideo, Uruguay
727   171.0                                           NaN
81    269.0                                 Milwaukee, WI
506     NaN  Guernsey / Montclair, NJ and/or Toledo, Ohio
285    96.0                                  New York, NY
594     NaN              Guernsey, England / Edgewood, RI

In [43]:
row_position_fifth = new_titanic_survival.iloc[4]
print(row_position_fifth)

pclass                           1.0
survived                         0.0
name         Artagaveytia, Mr. Ramon
sex                             male
age                             71.0
sibsp                            0.0
parch                            0.0
ticket                      PC 17609
fare                         49.5042
cabin                            NaN
embarked                           C
boat                             NaN
body                            22.0
home.dest        Montevideo, Uruguay
Name: 9, dtype: object

In [44]:
row_index_25 = new_titanic_survival.loc[25]
print(row_index_25)

pclass                       1.0
survived                     0.0
name         Birnbaum, Mr. Jakob
sex                         male
age                         25.0
sibsp                        0.0
parch                        0.0
ticket                     13905
fare                        26.0
cabin                        NaN
embarked                       C
boat                         NaN
body                       148.0
home.dest      San Francisco, CA
Name: 25, dtype: object

## Les index de colonne

In [46]:
new_titanic_survival.iloc[0,0]

1.0

In [48]:
# Indiquer toutes les lignes de la colonne 1 à 3
new_titanic_survival.iloc[:,0:3]

      pclass  survived                                               name
14       1.0       1.0               Barkworth, Mr. Algernon Henry Wilson
61       1.0       1.0  Cavendish, Mrs. Tyrell William (Julia Florence...
1235     3.0       0.0                                Svensson, Mr. Johan
135      1.0       0.0                          Goldschmidt, Mr. George B
9        1.0       0.0                            Artagaveytia, Mr. Ramon
...      ...       ...                                                ...
1297     3.0       0.0                             Wiseman, Mr. Phillippe
1302     3.0       0.0                                  Yousif, Mr. Wazli
1303     3.0       0.0                              Yousseff, Mr. Gerious
1305     3.0       0.0                              Zabour, Miss. Thamine
1309     NaN       NaN                                                NaN

[1310 rows x 3 columns]

In [50]:
# On cherche l'index de la ligne 83 de la colonne âge
new_titanic_survival.loc[83,"age"]

64.0

In [52]:
# On cherche l'index de la ligne 766 de la colonne pclass
new_titanic_survival.loc[766,"pclass"]

3.0

### Exercice

- Assigner la valeur d'intitulé de ligne 1100 pour la colonne "age" de new_titanic_survival à la variable row_index_1100_age.

- Assigner la valeur d'intitulé de ligne 25 pour la colonne "survived" de new_titanic_survival à la variable row_index_25_survived.

- Assigner les 5 premières lignes et 3 premières colonnes de new_titanic_survival à la variable five_rows_three_cols.

- Afficher tous les résultats.

In [56]:
row_index_1100_age = new_titanic_survival.loc[1100,"age"]
row_index_25_survived = new_titanic_survival.loc[25,"survived"]
five_rows_three_cols = new_titanic_survival.iloc[0:5,0:3]
print(row_index_1100_age)
print(row_index_25_survived)
print(five_rows_three_cols)

29.0
0.0
      pclass  survived                                               name
14       1.0       1.0               Barkworth, Mr. Algernon Henry Wilson
61       1.0       1.0  Cavendish, Mrs. Tyrell William (Julia Florence...
1235     3.0       0.0                                Svensson, Mr. Johan
135      1.0       0.0                          Goldschmidt, Mr. George B
9        1.0       0.0                            Artagaveytia, Mr. Ramon

## Réindexer les lignes d'un dataframe

In [57]:
new_titanic_survival

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1302,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1303,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# DataFrame.reset_index(drop=True)

In [63]:
new_titanic_survival.reset_index()

,index,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
1,61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
2,1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
3,135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
4,9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,1297,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1306,1302,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1307,1303,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1308,1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Exercice

- Ré-indexer le dataframe new_titanic_survival pour que la première ligne commence à 0 et supprimer l'ancien indexage.

- Assigner le résultat à la variable titanic_reindexed.

- Afficher les 5 premières lignes et 3 premières colonnes de titanic_reindexed.

In [66]:
titanic_reindexed = new_titanic_survival.reset_index(drop=True)
titanic_reindexed

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
1,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
2,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
3,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
4,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1306,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1307,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
# Afficher les 5 premières lignes et 3 premières colonnes de titanic_reindexed
titanic_reindexed.iloc[0:5,0:3]

   pclass  survived                                               name
0     1.0       1.0               Barkworth, Mr. Algernon Henry Wilson
1     1.0       1.0  Cavendish, Mrs. Tyrell William (Julia Florence...
2     3.0       0.0                                Svensson, Mr. Johan
3     1.0       0.0                          Goldschmidt, Mr. George B
4     1.0       0.0                            Artagaveytia, Mr. Ramon

## Appliquer des fonctions sur un DataFrame

In [68]:
# DataFrame.apply()

In [69]:
# Créer une fonction qui retourne le 100e élément

def row_100(column):
    # extraire le 100e élement d'une colonne
    item = column.iloc[99]
    return item

In [70]:
# retourne la 100eme élément (ligne) de chaque colonne
row_100_var = titanic_survival.apply(row_100)
row_100_var

pclass                                                     1.0
survived                                                   1.0
name         Duff Gordon, Lady. (Lucille Christiana Sutherl...
sex                                                     female
age                                                       48.0
sibsp                                                      1.0
parch                                                      0.0
ticket                                                   11755
fare                                                      39.6
cabin                                                      A16
embarked                                                     C
boat                                                         1
body                                                       NaN
home.dest                                       London / Paris
dtype: object

## Appliquer des fonctions sur un DataFrame

- Ecrire une fonction qui compte le nombre d'éléments manquants d'un objet Series.

- Utiliser la méthode DataFrame.apply() pour appliquer votre fonction sur titanic_survival.

- Assigner le résultat à la variable column_null_count.

- Afficher le résultat.

In [76]:
# Définir un paramétres
def null_count(column):
    # Trouver les valeurs manquante avec la libraire pd et la méthode null
    column_null = pd.isnull(column)
    null = column[column_null]
    return len(null)

In [74]:
# Permettre de donner le nombre de valeur manquantes pour chaque colonne
column_null_count = titanic_survival.apply(null_count)
print(column_null_count)

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

## Appliquer une fonction à une ligne

In [84]:
# DataFrame.apply(function, axis=1)
# axis=1 : Sur chaque ligne de notre DataFrame

In [85]:
# Création d'une fonction en définissant le paramétres lignes
def is_minor(row):
    if row["age"] < 18: 
        return True
    else:
        return False

In [86]:
# Appliquer la fonction 
minors = titanic_survival.apply(is_minor, axis=1)
minors

0       False
1        True
2        True
3       False
4       False
        ...
1305    False
1306    False
1307    False
1308    False
1309    False
Length: 1310, dtype: bool

In [90]:
# Création d'une fonction
def which_class(row):
    # On va chercher les éléments de la colonne pclass
    pclass = row["pclass"]

# On vérifie si la valeur est manquante dans la colonne pclass avec la libraire pd.isnull ensuite on définie des conditions
    if pd.isnull(pclass): 
        return "Unknown"
    elif pclass == 1: 
        return "First Class"
    elif pclass == 2: 
        return "Second Class"
    else:
        return "Third Class"

In [89]:
classes = titanic_survival.apply(which_class, axis=1)
classes

0       First Class
1       First Class
2       First Class
3       First Class
4       First Class
           ...
1305    Third Class
1306    Third Class
1307    Third Class
1308    Third Class
1309        Unknown
Length: 1310, dtype: object

### Exercice

- Créer une fonction qui retourne la chaine de caractères "minor" pour quelqu'un de moins de 18 ans, "adult" si son age est supérieur ou égal à 18 et "unknown" si la valeur est manquante.

- Utiliser cette fonction avec la méthode apply() pour trouver l'intitulé correct pour chaque apssager du dataframe titanic_survival.

- Assigner le résultat à la variable age_labels.

- Afficher le résultat.

In [92]:
def minor_age(row): 
    age = row["age"]

    if pd.isnull(age): 
        return "unknown"
    elif age < 18:
        return "minor"
    else:
        return "adult"

In [95]:
age_def = titanic_survival.apply(minor_age, axis=1)
age_def

0         adult
1         minor
2         minor
3         adult
4         adult
         ...
1305    unknown
1306      adult
1307      adult
1308      adult
1309    unknown
Length: 1310, dtype: object

## Pratique: Calculer le pourcentage de survie par groupe d'âge

- Ajouter la colonne "age_labels" au dataframe titanic_survival contenant la variable age_labels qu'on a créé dans la vidéo précédente.

- Créer une table pivot qui calcule la moyenne de chance de survie (colonne "survived") pour chaque groupe d'âge (colonne "age_labels") du dataframe titanic_survival.

- Assigner l'objet Series résultant à la variable age_group_survival.

- Afficher le résultat.

In [97]:
# Ajouter une nouvelle colonne dans le dataframe
titanic_survival["age_def"] = age_def

#Créer un pivot table
age_group_survival = titanic_survival.pivot_table(index="age_def", values="survived")

print(age_group_survival)

         survived
age_def
adult    0.387892
minor    0.525974
unknown  0.277567