# Tout sur les Series avec Pandas

## Les structures de données

- Lire le fichier "fandango_score_comparison.csv" dans un dataframe qu'on nommera fandango.

- Afficher les 2 premières lignes de fandango.

In [1]:
import pandas as pd

fandango = pd.read_csv("fandango_score_comparison.csv")
fandango

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.30,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.00,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.50,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.20,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.40,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.70,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
142,'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.10,...,3.60,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
143,"Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.90,...,3.70,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0
144,Gett: The Trial of Viviane Amsalem (2015),100,81,90,7.3,7.8,3.5,3.5,5.00,4.05,...,3.90,5.0,4.0,4.5,3.5,4.0,19,1955,59,0.0
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

In [3]:
fandango.iloc[0:2]
# ou fandango.head(2)

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5

## Indexage avec des entiers

- Sélectionner la colonne "FILM" et assigner la à la variable series_film puis afficher les 5 premières valeurs.

- Faire de même avec la colonne "RottenTomatoes" et assigner la à la variable series_rt puis afficher les 5 premières valeurs.

In [9]:
series_film = fandango["FILM"][0:5]
# ou print(series_film[0:5])
series_film

0    Avengers: Age of Ultron (2015)
1                 Cinderella (2015)
2                    Ant-Man (2015)
3            Do You Believe? (2015)
4     Hot Tub Time Machine 2 (2015)
Name: FILM, dtype: object

In [12]:
series_rt = fandango["RottenTomatoes"]
print(series_rt[0:5])

0    74
1    85
2    80
3    18
4    14
Name: RottenTomatoes, dtype: int64

## Personnaliser son indexage

In [14]:
# series_custom[["Minions (2015)", "Leviatan (2014)"]]

In [15]:
# Series(data=Series.values, index=Series.values)

- Créer un objet Series qu'on nommera series_custom qui aura un index de chaines de caractères (basé sur le nom des films qu'on assignera à la variable film_names) et contiendra toutes les notes RottenTomatoes de series_rt qu'on assignera à la variable rt_scores.

    - Attention de bien utiliser des listes de valeurs pour nos 2 paramètres de la méthode Series()

    - Ne pas oublier d'importer l'objet Series depuis pandas

In [19]:
# Importer l'objet Series depuis pandas
from pandas import Series

In [21]:
series_film = fandango["FILM"]
series_rt = fandango["RottenTomatoes"]

film_names = series_film.values
rt_scores = series_rt.values

series_custom = Series(rt_scores, index=film_names)

In [26]:
# Accéder à des données depuis les positions
series_custom[5:11]

The Water Diviner (2015)             63
Irrational Man (2015)                42
Top Five (2014)                      86
Shaun the Sheep Movie (2015)         99
Love & Mercy (2015)                  89
Far From The Madding Crowd (2015)    84
dtype: int64

## Réindexer un objet Series

In [28]:
# series.reindex()

In [32]:
# Pour retourner une liste d'index actuel = series_custom.index

In [33]:
# Pour trier la liste d'index = sorted()

### Exercice

- Créer la liste original_index contenant l'index actuel à partir de l'attribut index.

- Trier cet index en utilisant la méthode sorted() et assigner le résultat à la variable sorted_index.

- Puis appliquer la méthode reindex() à notre Series custom_series afin de réindexer selon l'index de sorted_index.

- Stocker le résultat dans la variable sorted_by_index.

- Afficher le résultat.

In [34]:
# Créer la liste original_index contenant l'index actuel à partir de l'attribut index.
original_index = series_custom.index

# Trier cet index en utilisant la méthode sorted() et assigner le résultat à la variable sorted_index.
sorted_index = sorted(original_index)

# Appliquer la méthode reindex() à notre Series custom_series afin de réindexer selon l'index de sorted_index.
sorted_by_index = series_custom.reindex(sorted_index)

In [36]:
# Afficher les films de maniére alphabétique
print(sorted_by_index)

'71 (2015)                          97
5 Flights Up (2015)                 52
A Little Chaos (2015)               40
A Most Violent Year (2014)          90
About Elly (2015)                   97
                                    ..
What We Do in the Shadows (2015)    96
When Marnie Was There (2015)        89
While We're Young (2015)            83
Wild Tales (2014)                   96
Woman in Gold (2015)                52
Length: 146, dtype: int64

## Trier un objet Series

In [38]:
# Series.sort_index() = Trier un objet Series par son index

# Series.sort_values() = Trier un objet Series par ses valeurs

### Exercice

- Trier la Series series_custom par index en utilisant la méthode sort_index() et assigner le résultat à la variable sc2.

- Trier la Series series_custom par valeurs et assigner le résultat à la variable sc3.

- Afficher les 10 premières valeurs de sc2 et sc3.

In [40]:
# Trier la series_custom par index
sc2 = series_custom.sort_index()
print(sc2)

'71 (2015)                          97
5 Flights Up (2015)                 52
A Little Chaos (2015)               40
A Most Violent Year (2014)          90
About Elly (2015)                   97
                                    ..
What We Do in the Shadows (2015)    96
When Marnie Was There (2015)        89
While We're Young (2015)            83
Wild Tales (2014)                   96
Woman in Gold (2015)                52
Length: 146, dtype: int64

In [42]:
# Trier la series_custom par valeurs
sc3 = series_custom.sort_values()
print(sc3)

Paul Blart: Mall Cop 2 (2015)                  5
Hitman: Agent 47 (2015)                        7
Hot Pursuit (2015)                             8
Fantastic Four (2015)                          9
Taken 3 (2015)                                 9
                                            ...
Song of the Sea (2014)                        99
Phoenix (2015)                                99
Selma (2014)                                  99
Seymour: An Introduction (2015)              100
Gett: The Trial of Viviane Amsalem (2015)    100
Length: 146, dtype: int64

In [48]:
# Afficher les 10 premiers valeurs de sc2
sc2.head(10)

'71 (2015)                    97
5 Flights Up (2015)           52
A Little Chaos (2015)         40
A Most Violent Year (2014)    90
About Elly (2015)             97
Aloha (2015)                  19
American Sniper (2015)        72
American Ultra (2015)         46
Amy (2015)                    97
Annie (2014)                  27
dtype: int64

In [49]:
# Afficher les 10 premiers valeurs de sc3
sc3.head(10)

Paul Blart: Mall Cop 2 (2015)     5
Hitman: Agent 47 (2015)           7
Hot Pursuit (2015)                8
Fantastic Four (2015)             9
Taken 3 (2015)                    9
The Boy Next Door (2015)         10
The Loft (2015)                  11
Unfinished Business (2015)       11
Mortdecai (2015)                 12
Seventh Son (2015)               12
dtype: int64

## Transformation de colonnes

In [50]:
series_custom/10

Avengers: Age of Ultron (2015)                7.4
Cinderella (2015)                             8.5
Ant-Man (2015)                                8.0
Do You Believe? (2015)                        1.8
Hot Tub Time Machine 2 (2015)                 1.4
                                             ...
Mr. Holmes (2015)                             8.7
'71 (2015)                                    9.7
Two Days, One Night (2014)                    9.7
Gett: The Trial of Viviane Amsalem (2015)    10.0
Kumiko, The Treasure Hunter (2015)            8.7
Length: 146, dtype: float64

In [51]:
import numpy as np

In [53]:
# Additionner chaque valeur avec une autre (le double de la valeur)
np.add(series_custom, series_custom)

Avengers: Age of Ultron (2015)               148
Cinderella (2015)                            170
Ant-Man (2015)                               160
Do You Believe? (2015)                        36
Hot Tub Time Machine 2 (2015)                 28
                                            ...
Mr. Holmes (2015)                            174
'71 (2015)                                   194
Two Days, One Night (2014)                   194
Gett: The Trial of Viviane Amsalem (2015)    200
Kumiko, The Treasure Hunter (2015)           174
Length: 146, dtype: int64

In [54]:
# Appliquer la fonction sinus à chaque valeur
np.sin(series_custom)

Avengers: Age of Ultron (2015)              -0.985146
Cinderella (2015)                           -0.176076
Ant-Man (2015)                              -0.993889
Do You Believe? (2015)                      -0.750987
Hot Tub Time Machine 2 (2015)                0.990607
                                               ...
Mr. Holmes (2015)                           -0.821818
'71 (2015)                                   0.379608
Two Days, One Night (2014)                   0.379608
Gett: The Trial of Viviane Amsalem (2015)   -0.506366
Kumiko, The Treasure Hunter (2015)          -0.821818
Length: 146, dtype: float64

In [55]:
# Retourner la valeur max (valeur unique, non pas la series)
np.max(series_custom)

100

## Exercice

- Normaliser la Series series_custom (échelle de notes de 0 à 100) pour obtenir une échelle de notes de 0 à 5 en divisant l'objet par 20.

- Assigner le nouvel objet Series à la variable series_normalized.

- Afficher le résultat.

In [61]:
# Afficher 100 valeurs de la series_custom en divisant l'objet par 20 
series_normalized = ((series_custom/20)[0:100])
print(series_normalized)

Avengers: Age of Ultron (2015)    3.70
Cinderella (2015)                 4.25
Ant-Man (2015)                    4.00
Do You Believe? (2015)            0.90
Hot Tub Time Machine 2 (2015)     0.70
                                  ...
The Salt of the Earth (2015)      4.80
Song of the Sea (2014)            4.95
Fifty Shades of Grey (2015)       1.25
Get Hard (2015)                   1.45
Focus (2015)                      2.85
Length: 100, dtype: float64

## Comparer et filter

In [65]:
# Afficher tous les films supérieur à 50 sous la forme de booléen
series_custom > 50

Avengers: Age of Ultron (2015)                True
Cinderella (2015)                             True
Ant-Man (2015)                                True
Do You Believe? (2015)                       False
Hot Tub Time Machine 2 (2015)                False
                                             ...
Mr. Holmes (2015)                             True
'71 (2015)                                    True
Two Days, One Night (2014)                    True
Gett: The Trial of Viviane Amsalem (2015)     True
Kumiko, The Treasure Hunter (2015)            True
Length: 146, dtype: bool

In [64]:
# Afficher tous les films surpérieur à 50 + la note 
series_greater_than_50 = series_custom[series_custom > 50]
series_greater_than_50

Avengers: Age of Ultron (2015)                74
Cinderella (2015)                             85
Ant-Man (2015)                                80
The Water Diviner (2015)                      63
Top Five (2014)                               86
                                            ...
Mr. Holmes (2015)                             87
'71 (2015)                                    97
Two Days, One Night (2014)                    97
Gett: The Trial of Viviane Amsalem (2015)    100
Kumiko, The Treasure Hunter (2015)            87
Length: 94, dtype: int64

## Exercice

- Assigner à la variable criteria_one le critère des valeurs de series_custom supérieures à 50.

- Assigner à la variable criteria_two le critère des valeurs de series_custom inférieures à 75.

- Retourner un nouvel objet Series filtré qu'on nommera both_criteria qui contient seulement les valeurs pour lesquelles les 2 critères sont vrais.

- Afficher ce dernier résultat.

In [70]:
# Afficher les valeurs de series_custom supérieures à 50 
criteria_one = [series_custom > 50]
criteria_one

[Avengers: Age of Ultron (2015)                True
 Cinderella (2015)                             True
 Ant-Man (2015)                                True
 Do You Believe? (2015)                       False
 Hot Tub Time Machine 2 (2015)                False
                                              ...
 Mr. Holmes (2015)                             True
 '71 (2015)                                    True
 Two Days, One Night (2014)                    True
 Gett: The Trial of Viviane Amsalem (2015)     True
 Kumiko, The Treasure Hunter (2015)            True
 Length: 146, dtype: bool]

In [71]:
# Afficher les valeurs de series_custom inférieurs à 75 
criteria_two = [series_custom < 75]
criteria_two

[Avengers: Age of Ultron (2015)                True
 Cinderella (2015)                            False
 Ant-Man (2015)                               False
 Do You Believe? (2015)                        True
 Hot Tub Time Machine 2 (2015)                 True
                                              ...
 Mr. Holmes (2015)                            False
 '71 (2015)                                   False
 Two Days, One Night (2014)                   False
 Gett: The Trial of Viviane Amsalem (2015)    False
 Kumiko, The Treasure Hunter (2015)           False
 Length: 146, dtype: bool]

In [74]:
# Tous les films comprit entre 50 et 75

criteria_one = series_custom > 50
criteria_two = series_custom < 75
both_criteria = series_custom[criteria_one & criteria_two]
both_criteria

Avengers: Age of Ultron (2015)                                            74
The Water Diviner (2015)                                                  63
Unbroken (2014)                                                           51
Southpaw (2015)                                                           59
Insidious: Chapter 3 (2015)                                               59
The Man From U.N.C.L.E. (2015)                                            68
Run All Night (2015)                                                      60
5 Flights Up (2015)                                                       52
Welcome to Me (2015)                                                      71
Saint Laurent (2015)                                                      51
Maps to the Stars (2015)                                                  60
Pitch Perfect 2 (2015)                                                    67
The Age of Adaline (2015)                                                 54
The DUFF (2015)                                                           71
Ricki and the Flash (2015)                                                64
Unfriended (2015)                                                         60
American Sniper (2015)                                                    72
The Hobbit: The Battle of the Five Armies (2014)                          61
Paper Towns (2015)                                                        55
Big Eyes (2014)                                                           72
Maggie (2015)                                                             54
Focus (2015)                                                              57
The Second Best Exotic Marigold Hotel (2015)                              62
The 100-Year-Old Man Who Climbed Out the Window and Disappeared (2015)    67
Escobar: Paradise Lost (2015)                                             52
Into the Woods (2014)                                                     71
Inherent Vice (2014)                                                      73
Magic Mike XXL (2015)                                                     62
Woman in Gold (2015)                                                      52
The Last Five Years (2015)                                                60
Jurassic World (2015)                                                     71
Minions (2015)                                                            54
Spare Parts (2015)                                                        52
dtype: int64

## Alignement des données

- Créer la Series rt_critics qui index les valeurs des notes de la colonne RottenTomatoes (notes des critiques) avec comme index le nom des films (colonne FILM).

- Créer la Series rt_users qui index les valeurs des notes de la colonne RottenTomatoes_User (note des utilisateurs) avec comme index le nom des films (colonne FILM).

- rt_critics et rt_users sont donc 2 objets Series contenant la moyenne des notes des critiques et des utilisateurs pour chaque film.

- Puisque chaque Series utilise le même index (correspondant aux noms des films), utiliser des opérations mathématiques pour retourner la moyenne des notes des critiques et des utilisateurs pour chaque film.

- Assigner la Series résultante à la variable rt_mean.

- Afficher le résultat.

In [80]:
# index les valeurs des notes de la colonne RottenTomatoes et le nom des films de le colonne FILM 
rt_critics = Series(fandango["RottenTomatoes"].values, index=fandango["FILM"])
rt_users = Series(fandango["RottenTomatoes_User"].values, index=fandango["FILM"])

In [81]:
# Calculer la moyenne des 2 objets Series (moyenne des critiques & Utilisateurs)
rt_mean = (rt_critics + rt_users)/2

print(rt_mean)

FILM
Avengers: Age of Ultron (2015)               80.0
Cinderella (2015)                            82.5
Ant-Man (2015)                               85.0
Do You Believe? (2015)                       51.0
Hot Tub Time Machine 2 (2015)                21.0
                                             ...
Mr. Holmes (2015)                            82.5
'71 (2015)                                   89.5
Two Days, One Night (2014)                   87.5
Gett: The Trial of Viviane Amsalem (2015)    90.5
Kumiko, The Treasure Hunter (2015)           75.0
Length: 146, dtype: float64